### ISSUE TITLE
Greatly increased error logging over the last few days

### ISSUE THREAD

**Issue by Splaktar** [GoogleCloudPlatform/cloud-debug-nodejs#152] opened 2016-09-30 14:33 UTC
We've been using this library for a few weeks now (`"@google/cloud-debug": "0.8.4"`) and we've occasionally seen some errors about failing to make a connection, but those have generally been a few per day. As of 9/28 or so, we're seeing the following message once per minute:

```
ERROR:@google/cloud-debug: Failed to re-register debuggee: Error: getaddrinfo ENOTFOUND clouddebugger.googleapis.com clouddebugger.googleapis.com:443
```

We've also been seeing this message a lot:
```
 "ERROR:@google/cloud-debug: Unable to fetch breakpoints – stopping fetcher { [Error: getaddrinfo ENOTFOUND clouddebugger.googleapis.com clouddebugger.googleapis.com:443]"
```

Also around 3am-9am today and 5:23pm-11pm on 9/29, we were seeing this message once per minute:
```
"ERROR:@google/cloud-debug: Failed to re-register debuggee: Error: getaddrinfo ENOTFOUND accounts.google.com accounts.google.com:443"
```

We also saw this message just once on 9/29:
```
"ERROR:@google/cloud-debug: Unable to fetch breakpoints – stopping fetcher [Error: unable to list breakpoints, status code 401]"
```

On 9/28, we were seeing, but only a few times per day:
```
 "ERROR:@google/cloud-debug: Unable to fetch breakpoints – stopping fetcher [Error: unable to list breakpoints, status code 504]"
```

We have the ENV var defined for `GCLOUD_PROJECT=<our project name>`. We also have a JSON service account key which is pointed to by `GOOGLE_APPLICATION_CREDENTIALS=<path>`. We also have our `require('@google/cloud-debug');` statement at the top of our `index.ts/js`.

Finally, our NodeJS project is in TypeScript, so we've never been able to get the debugger to work yet. Is the guidance that we source control our transpiled ES5 source code? Are there any guides for using TypeScript with Cloud Debug and NodeJS?

Thank you!

**Comment by ofrobots** [comment] 2016-09-30 17:00
Are you continuing to experience these errors? Those errors suggest that the debug agent was able to DNS resolve or talk to the Debug API. This sounds like a networking issue since the API resolves locally for me and there was no outage recently. Which environment is your application running in (GAE, GKE, GCE)?

As for typescript, we do have experimental support for debugging typescript-based projects. We haven't had too much real world testing and feedback though. Let me draft a quick guide for you to try and we can go from there.

**Comment by Splaktar** [comment] 2016-09-30 23:44
Running in GAE Flexible Environment with NodeJS default runtime.

That guide would be excellent and I'd love to provide some real world feedback.

**Comment by ofrobots** [comment] 2016-10-02 22:48
@Splaktar Here is a very brief guide to debugging typescript code:

app.ts
```typescript
import * as debug from '@google/cloud-debug'
import * as express from 'express';
var app = express();
app.get('/', (req, res) => {
  res.status(200).send(`express + ${debug}`);
});
app.get('/hello/:name', (req, res) => {
  var msg : string = `Hello ${req.params.name}`;
  res.status(200).send(msg);
});

app.listen(process.env.PORT || 8080, function() {
  console.log('App started');
});

export var App = app;
```

1. Make sure your have configured the typescript compiler to generate sourcemaps. You can do this by either using the `--sourceMap` command line option or by setting the configuration appropriately in your [tsconfig.json](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html).
1. Ensure that the generated sourcemap files (e.g.`app.js.map`) get deployed along with the generated javascript. (The source typescript files do not have to be deployed.)
1. Make sure the original typescript source is available to the Debug UI. (The generated JavaScript and map files do not have to be available in the Debug UI.)
1. You should be able to set a breakpoint in your typescript source code.

In the example below, you can see that I have set a breakpoint in app.ts:9.
<img width="1120" alt="screen shot 2016-10-02 at 1 10 36 pm" src="https://cloud.githubusercontent.com/assets/79017/19023345/b856a606-88a1-11e6-85ac-e7cb5f9aaf42.png">

In the snapshot section on the right you can see that app.ts:9 was resolved to app.js:9. (BTW, I noticed there is an off-by-one bug here; the actual breakpoint should have been set at app.js:10. I have opened bug #153 for this.) 

This support is experimental, and hasn't gotten too much real world testing. Please do try out and open bugs if you run into issues.

**Comment by matthewloring** [comment] 2016-10-03 17:34
@Splaktar There are not any known outages or issues to account for the increased error frequency you are seeing. Would you be able to share your project id and project number with me so that we can investigate further. You can post them here or send them to me over email if you prefer (email is linked on my github profile).

**Comment by matthewloring** [comment] 2016-10-07 17:01
@Splaktar Just wanted to ping this. Would you be able to share your project id and project number so that I can try to diagnose this further?

**Comment by Splaktar** [comment] 2016-10-12 04:14
@matthewloring yes, email sent to you. Sorry for the delay but we were evacuated for Hurricane Matthew. Things are slowly starting to get back to normal.

When looking at the project, please note that we've removed cloud-debug for now to avoid this issue. But the logs from 9/28 and 9/29 should still be there.

**Comment by matthewloring** [comment] 2016-10-12 04:59
I've passed this information on and will let you know when we have more information. Hope all is well!

**Comment by Splaktar** [comment] 2016-10-14 17:58
So today we upgraded from `"google-cloud": "0.40.0"` to `"google-cloud": "0.41.2"` and deployed. Then we started seeing what seems like a similar error in stderr, even with cloud-debug not installed/enabled.

```
10:41:31.000
E1014 14:41:25.222190850 24 plugin_credentials.c:67] Getting metadata from plugin failed with error: getaddrinfo ENOTFOUND accounts.google.com accounts.google.com:443
10:41:31.000
E1014 14:41:25.346963414 24 client_auth_filter.c:93] Client side authentication failure: getaddrinfo ENOTFOUND accounts.google.com accounts.google.com:443
10:41:31.000
Auth error:Error: getaddrinfo ENOTFOUND accounts.google.com accounts.google.com:443
```

Is this an issue with https://github.com/google/google-auth-library-nodejs?

**Comment by ofrobots** [comment] 2016-10-14 19:51
@Splaktar `ENOTFOUND` is returned when the OS is not able to do a DNS resolution. This seems to be a networking issue of some sort. For a networking issue, It was surprising why you were seeing resolve failures only for clouddebugger.googleapis.com. The new failures now make a bit more sense, but still don't point to a clear cause. We are unable to reproduce these failures.

A few questions:

1. If you revert back to `0.40.0` of `google-cloud`, do you still see these errors.
2. Do you see these errors on this project only, or on other projects too?

**Comment by ofrobots** [comment] 2016-10-14 20:03
@Splaktar if you get a chance, can you try with the following `force-family-4` branch of this module? This forces the use of ipv4 instead of ipv6 in case that is relevant somehow. To use you can `npm install` as follows:

```sh
npm install --save git://github.com/ofrobots/cloud-debug-nodejs.git#force-family-4
```

**Comment by Splaktar** [comment] 2016-10-14 20:05
This issue seems like it could be related as well, https://github.com/google/google-api-nodejs-client/issues/513.

@ofrobots I made a mistake about the upgrading to `"google-cloud": "0.41.2"`. These timestamps are from before the upgrade, so they are from `0.40.0`. I edited the above post about an hour ago to correct that.

This is the only project that we have using GAE Flexible Environment with the NodeJS Runtime. There are no special networking / DNS settings in this project or firewalls related to this authentication. It seems to work sporadically and then other times fails frequently.

This is part of the GAE Flexible Environment and NodeJS runtime, so it's not our OS or custom docker image or anything like that.

We are using the google-cloud library to access GCE, Pub/Sub, BigQuery, and more. Those calls are working just fine.

We're seeing issues with cloud-debug and cloud-trace:
```
ERROR:@google/cloud-trace: TraceWriter: error: { [Error: getaddrinfo ENOTFOUND accounts.google.com accounts.google.com:443]
code: 'ENOTFOUND',
errno: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'accounts.google.com',
host: 'accounts.google.com',
port: 443 }
```

I'm not sure what lib is causing the errors seen in https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/issues/152#issuecomment-253874867.

**Comment by Splaktar** [comment] 2016-10-14 20:16
We have the following relevant env vars defined as described in item 2 [here](https://github.com/GoogleCloudPlatform/cloud-debug-nodejs#running-elsewhere):
```
GCLOUD_PROJECT=our-project-name
GOOGLE_API_KEY=ApiKey
GOOGLE_APPLICATION_CREDENTIALS=lib/creds.json
```

**Comment by ofrobots** [comment] 2016-10-14 20:16
Thanks for the info – this is helpful in my understanding of the problem. If you're able to try the ipv4 experiment for cloud-debug, that would be very useful.

Those errors in https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/issues/152#issuecomment-253874867 look like they are coming from [gRPC](http://grpc.io) which is internally used by `google-cloud`.

**Comment by Splaktar** [comment] 2016-10-14 20:45
I've deployed your `force-family-4` branch along with an update to cloud-trace `0.5.8`. I'm not seeing any related errors yet, but I'll need to leave it for 24+ hours to see if they appear.

For your reference, here are the other tools that we're using in this project:
```
    "@google/cloud-debug": "git://github.com/ofrobots/cloud-debug-nodejs.git#force-family-4",
    "@google/cloud-trace": "0.5.8",
    "cors": "2.8.1",
    "csv-parse": "1.1.7",
    "devintent-mongoose-paginate": "5.0.4",
    "dotenv": "2.0.0",
    "express": "4.14.0",
    "express-paginate": "0.2.2",
    "firebase": "3.4.1",
    "google-cloud": "0.41.2",
    "lodash": "4.16.2",
    "mime": "1.3.4",
    "moment": "2.15.1",
    "mongoose": "4.6.2",
    "node-expat": "2.3.15",
    "request": "2.75.0",
    "request-promise": "4.1.1",
    "typescript": "2.0.3",
    "xml2js": "0.4.17"
```

**Comment by ofrobots** [comment] 2016-10-14 20:54
Thanks! The `force-family-4` branch ensures that all requests to only `clouddebugger.googleapis.com` go through ipv4.  I would be very curious to see if you get `ENOTFOUND` for this specific host. You may still see `ENOTFOUND` for other hosts, for example `accounts.google.com` (those are not affected by this experiment).

**Comment by ofrobots** [comment] 2016-10-17 23:58
@Splaktar Do you have an update on whether you are still seeing the errors with `clouddebugger.googleapis.com` the disable-ipv6 experiment?

**Comment by Splaktar** [comment] 2016-10-19 21:40
Not yet, I had to pull in the changes from https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/pull/159 in order to get cloud-debug working.

I can confirm that I'm still seeing the `clouddebugger.googleapis.com` issues atm w/o your `force-family-4` branch. But using that branch atm doesn't allow me to actually hit any breakpoints.

**Comment by dfcowell** [comment] 2016-10-21 04:59
I'm seeing the same issue resolving pubsub.googleapis.com using `google-cloud`. Started a few days ago. Each of the screenshots attached are from a different app running against the same Google Cloud project.

![image](https://cloud.githubusercontent.com/assets/1295890/19587070/8ebfba74-9785-11e6-92fb-f521515e1d86.png)
![image](https://cloud.githubusercontent.com/assets/1295890/19587088/a860273e-9785-11e6-8664-ffbff38320d5.png)
![image](https://cloud.githubusercontent.com/assets/1295890/19587106/ddd98112-9785-11e6-94e4-cf471ed8c129.png)

**Comment by ofrobots** [comment] 2016-10-21 16:39
@dfcowell Thanks for the report. We just rolled out a networking fix that *might* solve this issue although we aren't 100% sure as the issue is hard to reproduce at will. The fix will be picked up when you apps/vms are restarted/redeployed.

@Splaktar we'd be very interested in your feedback about continued occurrence once you have picked up the fix by redeploying. (Can you confirm that you are using `vm: true` in your `app.yaml`?)

**Comment by Splaktar** [comment] 2016-10-21 23:23
@ofrobots is stopping and starting of the GAE version enough? or do I have to actually re-deploy the code again via `gcloud app deploy`?

app.yaml
```
runtime: nodejs
vm: true
handlers:
- url: /.*
  script: IGNORED
  secure: always
```

**Comment by ofrobots** [comment] 2016-10-21 23:26
@Splaktar restart should be enough.

**Comment by Splaktar** [comment] 2016-10-21 23:36
OK, restart complete. These networking errors seem to have gotten worse over time. We deployed a few days ago and the system was working for at least 2 days. But a number of parts of the system (auto ingestion, pub/sub, etc) stopped working due to network errors at least 2 days ago and haven't worked until the restart that I just did. 

For example, the cron job should have hit an endpoint 3 times today to trigger ingestion. But instead of logs related to that endpoint being hit or ingestion happening, all I have is a stdout full of `Error: getaddrinfo ENOTFOUND clouddebugger.googleapis.com clouddebugger.googleapis.com:443` and a stderr full of `Getting metadata from plugin failed with error: getaddrinfo ENOTFOUND accounts.google.com accounts.google.com:443`.

**Comment by ofrobots** [comment] 2016-10-21 23:43
@Splaktar are those errors about `clouddebugger.google.com` and `accounts.google.com` from before or after the restart?

**Comment by Splaktar** [comment] 2016-10-21 23:44
From the last 48 hours prior to the restart.

**Comment by ofrobots** [comment] 2016-10-21 23:49
@Splaktar Okay, please report back if you see more errors.

**Comment by dfcowell** [comment] 2016-10-22 07:31
Restarting my cluster seems to have picked up this latest fix and the DNS issues are sorted. Thanks! :) Still seeing some other networking-related weirdness (frequent socket hang-ups) but they appear to be unrelated to the DNS issue.

**Comment by Splaktar** [comment] 2016-10-23 01:45
24 hours with no errors at all related to DNS lookups! Thanks! I'll let you know if this changes.

**Comment by ofrobots** [comment] 2016-10-26 23:42
Closing. Please re-open if you think this is still an issue.

**Closed by ofrobots** 2016-10-26 23:42 UTC
